// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace DFC.Digital.Service.AzureSearch.IntegrationTests.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SingleTermDerivativesWithSuffixReturnsJobprofilesBasedUponRelevanceToSerchTermEnteredFeature : Xunit.IClassFixture<SingleTermDerivativesWithSuffixReturnsJobprofilesBasedUponRelevanceToSerchTermEnteredFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SingleTermDerivativeSearch.feature"
#line hidden
        
        public SingleTermDerivativesWithSuffixReturnsJobprofilesBasedUponRelevanceToSerchTermEnteredFeature(SingleTermDerivativesWithSuffixReturnsJobprofilesBasedUponRelevanceToSerchTermEnteredFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SingleTermDerivatives with suffix returns jobprofiles based upon relevance to ser" +
                    "ch term entered", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.TheoryAttribute(DisplayName="[DFC-5229] All JobProfiles which have search term derivative against the Title on" +
            " DIFFERENT profiles")]
        [Xunit.TraitAttribute("FeatureTitle", "SingleTermDerivatives with suffix returns jobprofiles based upon relevance to ser" +
            "ch term entered")]
        [Xunit.TraitAttribute("Description", "[DFC-5229] All JobProfiles which have search term derivative against the Title on" +
            " DIFFERENT profiles")]
        [Xunit.InlineDataAttribute("childminding", "Childminder", new string[0])]
        [Xunit.InlineDataAttribute("counselling", "Counsellor", new string[0])]
        [Xunit.InlineDataAttribute("Optometry", "Optomotrist", new string[0])]
        [Xunit.InlineDataAttribute("policing", "Police constable", new string[0])]
        [Xunit.InlineDataAttribute("Advertiser", "Advertising copywriter", new string[0])]
        [Xunit.InlineDataAttribute("Advertiser", "Advertising art director", new string[0])]
        [Xunit.InlineDataAttribute("Advertiser", "Advertising media planner", new string[0])]
        [Xunit.InlineDataAttribute("Advertiser", "Advertising account executive", new string[0])]
        [Xunit.InlineDataAttribute("Archaeology", "Archaeologist", new string[0])]
        [Xunit.InlineDataAttribute("pharmacology", "Pharmacologist", new string[0])]
        [Xunit.InlineDataAttribute("zoology", "Zoologist", new string[0])]
        [Xunit.InlineDataAttribute("administer", "Payroll administrator", new string[0])]
        [Xunit.InlineDataAttribute("administer", "Sales administrator", new string[0])]
        [Xunit.InlineDataAttribute("administer", "Pensions administrator", new string[0])]
        [Xunit.InlineDataAttribute("administer", "Database administrator", new string[0])]
        [Xunit.InlineDataAttribute("administer", "Arts administrator", new string[0])]
        [Xunit.InlineDataAttribute("biology", "Biologist", new string[0])]
        [Xunit.InlineDataAttribute("biology", "Plant biologist", new string[0])]
        [Xunit.InlineDataAttribute("diplomacy", "Diplomatic service officer", new string[0])]
        [Xunit.InlineDataAttribute("ecology", "Ecologist", new string[0])]
        [Xunit.InlineDataAttribute("farming", "Farmer", new string[0])]
        [Xunit.InlineDataAttribute("farming", "Farm worker", new string[0])]
        [Xunit.InlineDataAttribute("farming", "Farm secretary", new string[0])]
        [Xunit.InlineDataAttribute("farming", "Fish farmer", new string[0])]
        [Xunit.InlineDataAttribute("Hydrotherapy", "Colon hydrotherapist", new string[0])]
        [Xunit.InlineDataAttribute("hypnotherapy", "Hypnotherapist", new string[0])]
        [Xunit.InlineDataAttribute("investor", "Road traffic accident investigator", new string[0])]
        [Xunit.InlineDataAttribute("investor", "Private investigator", new string[0])]
        [Xunit.InlineDataAttribute("investor", "Investment analyst", new string[0])]
        [Xunit.InlineDataAttribute("landscaping", "Landscape architect", new string[0])]
        [Xunit.InlineDataAttribute("landscaping", "Landscaper", new string[0])]
        [Xunit.InlineDataAttribute("landscaping", "Landscape gardener", new string[0])]
        [Xunit.InlineDataAttribute("laundrette", "Laundry worker", new string[0])]
        [Xunit.InlineDataAttribute("Meteorology", "Meteorologist", new string[0])]
        [Xunit.InlineDataAttribute("Nanotechnology", "Nanotechnologist", new string[0])]
        [Xunit.InlineDataAttribute("offenders", "Youth offending service officer", new string[0])]
        [Xunit.InlineDataAttribute("performance", "Stunt performer", new string[0])]
        [Xunit.InlineDataAttribute("performance", "Circus performer", new string[0])]
        [Xunit.InlineDataAttribute("printing", "Print room operator", new string[0])]
        [Xunit.InlineDataAttribute("printing", "Print finisher", new string[0])]
        [Xunit.InlineDataAttribute("promoter", "Health promotion specialist", new string[0])]
        [Xunit.InlineDataAttribute("promoter", "Music promotions manager", new string[0])]
        [Xunit.InlineDataAttribute("screenwriting", "Screenwriter", new string[0])]
        [Xunit.InlineDataAttribute("Tattooer", "Tattooist", new string[0])]
        [Xunit.InlineDataAttribute("Technology", "Architectural technologist", new string[0])]
        [Xunit.InlineDataAttribute("Technology", "Garment technologist", new string[0])]
        [Xunit.InlineDataAttribute("Technology", "Critical care technologist", new string[0])]
        [Xunit.InlineDataAttribute("Technology", "Leather technologist", new string[0])]
        [Xunit.InlineDataAttribute("Technology", "Packaging technologist", new string[0])]
        public virtual void DFC_5229AllJobProfilesWhichHaveSearchTermDerivativeAgainstTheTitleOnDIFFERENTProfiles(string searchTerm, string title, string[] exampleTags)
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("[DFC-5229] All JobProfiles which have search term derivative against the Title on" +
                    " DIFFERENT profiles", null, exampleTags);
#line 2
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Title",
                        "AlternativeTitle",
                        "JobProfileSpecialism",
                        "HiddenAlternativeTitle",
                        "JobProfileCategories",
                        "Overview",
                        "CollegeRelevantSubjects",
                        "UniversityRelevantSubjects",
                        "ApprenticeshipRelevantSubjects",
                        "WYDDayToDayTasks",
                        "CareerPathAndProgression"});
            table1.AddRow(new string[] {
                        "Astronomer",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Criminal psychologist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Childminder",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Counsellor",
                        "Therapist, psychotherapist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Optomotrist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Police constable",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Advertising copywriter",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Advertising art director",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Advertising media planner",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Advertising account executive",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Archaeologist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Pharmacologist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Zoologist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Payroll administrator",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Sales administrator",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Pensions administrator",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Database administrator",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Arts administrator",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Biologist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Plant biologist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Diplomatic service officer",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Ecologist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Farmer",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Farm worker",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Farm secretary",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Fish farmer",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Colon hydrotherapist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Hypnotherapist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Road traffic accident investigator",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Private investigator",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Investment analyst",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Landscape architect",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Landscaper",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Landscape gardener",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Laundry worker",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Meteorologist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Nanotechnologist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Youth offending service officer",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Stunt performer",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Circus performer",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Print room operator",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Print finisher",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Health promotion specialist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Screenwriter",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Tattooist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Architectural technologist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "extrafields"});
            table1.AddRow(new string[] {
                        "Garment technologist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "extrafields",
                        ""});
            table1.AddRow(new string[] {
                        "Critical care technologist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "extrafields",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Leather technologist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "extrafields",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Packaging technologist",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "extrafields",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "Music promotions manager",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "",
                        ""});
#line 3
  testRunner.Given("the following job profiles exist:", ((string)(null)), table1, "Given ");
#line 56
  testRunner.When(string.Format("I search for search term \'{0}\'", searchTerm), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 57
  testRunner.Then(string.Format("the result will contain more than 1 result and \'{0}\' should be in the first page", title), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SingleTermDerivativesWithSuffixReturnsJobprofilesBasedUponRelevanceToSerchTermEnteredFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SingleTermDerivativesWithSuffixReturnsJobprofilesBasedUponRelevanceToSerchTermEnteredFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
