//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFC.Digital.Repository.ONET.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DFC_GDSONetSKATranslations_staging
    {
        public string ID { get; set; }
        public string Skill { get; set; }
        public string Description { get; set; }
        public string Translation { get; set; }
        public string Comments { get; set; }
    }
}
