//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFC.Digital.Repository.ONET.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DFC_SocMappings
    {
        public string JobProfile { get; set; }
        public string SocCode { get; set; }
        public string ONetCode { get; set; }
        public int QualityRating { get; set; }
    }
}
