//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFC.Digital.Repository.ONET.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class dwa_reference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dwa_reference()
        {
            this.tasks_to_dwas = new HashSet<tasks_to_dwas>();
        }
    
        public string element_id { get; set; }
        public string iwa_id { get; set; }
        public string dwa_id { get; set; }
        public string dwa_title { get; set; }
    
        public virtual content_model_reference content_model_reference { get; set; }
        public virtual iwa_reference iwa_reference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tasks_to_dwas> tasks_to_dwas { get; set; }
    }
}
