//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFC.Digital.Repository.ONET.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class green_occupations
    {
        public string onetsoc_code { get; set; }
        public string green_occupational_category { get; set; }
    
        public virtual occupation_data occupation_data { get; set; }
    }
}
