//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFC.Digital.Repository.ONET.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_zones
    {
        public string onetsoc_code { get; set; }
        public decimal job_zone { get; set; }
        public System.DateTime date_updated { get; set; }
        public string domain_source { get; set; }
    
        public virtual job_zone_reference job_zone_reference { get; set; }
        public virtual occupation_data occupation_data { get; set; }
    }
}
