//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFC.Digital.Repository.ONET.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey_booklet_locations
    {
        public string element_id { get; set; }
        public string survey_item_number { get; set; }
        public string scale_id { get; set; }
    
        public virtual content_model_reference content_model_reference { get; set; }
        public virtual scales_reference scales_reference { get; set; }
    }
}
