//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFC.Digital.Repository.ONET.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tools_and_technology
    {
        public string onetsoc_code { get; set; }
        public string t2_type { get; set; }
        public string t2_example { get; set; }
        public decimal commodity_code { get; set; }
        public string hot_technology { get; set; }
    
        public virtual occupation_data occupation_data { get; set; }
        public virtual unspsc_reference unspsc_reference { get; set; }
    }
}
