//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFC.Digital.Repository.ONET.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class unspsc_reference
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public unspsc_reference()
        {
            this.tools_and_technology = new HashSet<tools_and_technology>();
        }
    
        public decimal commodity_code { get; set; }
        public string commodity_title { get; set; }
        public decimal class_code { get; set; }
        public string class_title { get; set; }
        public decimal family_code { get; set; }
        public string family_title { get; set; }
        public decimal segment_code { get; set; }
        public string segment_title { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tools_and_technology> tools_and_technology { get; set; }
    }
}
